create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  invoice text unique not null,
  product_slug text not null,
  product text not null,
  item text not null,
  quantity integer not null default 1,
  subtotal bigint not null default 0,
  fee bigint not null default 0,
  discount bigint not null default 0,
  amount bigint not null,
  user_id text not null,
  server_id text default '',
  payment_method text not null,
  whatsapp text not null,
  promo text default '',
  payment_status text not null default 'PENDING',
  transaction_status text not null default 'PENDING',
  provider_reference text,
  payment_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists orders_invoice_idx on public.orders(invoice);
create index if not exists orders_created_at_idx on public.orders(created_at desc);

alter table public.orders enable row level security;
